# Generated by Django 4.2.5 on 2023-10-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mypost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField()),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=200)),
                ('caption', models.TextField()),
            ],
        ),
    ]
